### ISSUE TITLE
As a student who needs validation and reminders, I want to be debriefed on my achievements for that day and what is in store for me the next day.

### ISSUE THREAD

**Issue by Clouddoggo** [AY1920S2-CS2103T-F09-2/main#113]
- [X] Create NightDebriefWindow class and fxml file

- [X] Set NightDebriefWindow to show on application exit

- [X] Set NightDebriefWindow to display a list of complete tasks in the task list

- [x] Set NightDebriefWindow to display a list of tasks that were completed within the day

**Comment by yaojiethng** [comment]
@eedenong  Welcome message and night debrief
