### ISSUE TITLE
DG Feedback

### ISSUE THREAD

**Issue by ongaaron96** [AY1920S2-CS2103T-F09-2/main#302]
- Figure 1: Connect the arrows
- Update this diagram:
![image](https://user-images.githubusercontent.com/40322372/78453121-54ffba80-76c2-11ea-9695-e357a4fcba75.png)

### Task Grouping
- Diagrams are perfect
- Design Considerations Aspect 2: if no alternatives, then theres nothing to consider
- Figure 12: lifeline for `MainWindow`; should the activation bar for `CalendarPanel` be one continuous block?
![image](https://user-images.githubusercontent.com/40322372/78453271-259d7d80-76c3-11ea-9840-a657220b7139.png)

### Productivity
- Sequence diagrams are quite trivial as they are very similar to the SD in the above Logic component
- Think again if theres any more complex implementation in this component that you can explain
- If not, maybe you can add a suitable UML diagram to explain this:
![image](https://user-images.githubusercontent.com/40322372/78453376-d277fa80-76c3-11ea-98f2-3ba97813c6b8.png)

### Remider and Summary
- Same issues as **Productivity**

### Use Case
- Do not need to include trivial use cases (e.g. UC5, UC7)
- Some use cases can be improved: system should interact with the user after each user command. For the example below, the system can maybe display a message like "time stopped successfully".
![image](https://user-images.githubusercontent.com/40322372/78453541-00aa0a00-76c5-11ea-9eee-c9fee0fa63fd.png)
- All user commands should have a reaction from the system, even if its something trivial like "added successfully", to provide the user with feedback.
- Actions that users might regret should have a confirmation prompt (e.g. for delete and clear)

### Overall
- Very nice architecture diagrams at the beginning. However, be consistent with the styling (font, size, arrow types, box types, figure size) and colours of all the UML diagrams (e.g. same colour scheme used to represent Logic/Model components; same style for activity diagrams) across the whole document.
- Include Figure number for all UML diagrams
- For Sequence Diagrams, remove the lifeline after deletion
- For design considerations, after listing pros and cons, include a short paragraph explaining the reasons for the chosen implementation. Address the cons of the chosen implementation and the pros of the alternatives.
- Theres a lack of depth in explanation for most of your implementations. Try and find a more complex logic in your implementation and explain it, dont just create the same parsing command sequence diagram. Remember that you can also create class diagrams and activity diagrams if suitable.
-  In your explanations, if possible, you can add in non-UML diagrams (like in undo/redo) to help readers understand better.
- Remember to `code` out the keywords and be consistent.
- If you need more help / another review just let me know :)

**Comment by alam8064** [comment]
Thank you so much aaron!!
